const Map<String, String> englishPack = {
  'appTitle': 'ValueWheel',
  'welcome': 'Welcome to ValueWheel!',
  'featureSelectTitle': 'Choose what you want to do',
  'chooseModeTitle': 'Choose mode',
  'individualMode': 'Individual',
  'groupMode': 'Group',
  'askNumberLabel': 'How many values would you like to list?',
  'continueButton': 'Continue',
  'askWordsTitle': 'Enter Values',
  'askValueLabel': 'Give {index}. value',
  'amountLabel': 'The amount of values: {amount}',
  'compareLabel': 'Choose which one is more valuable.',
  'compareTitle': 'Comparison done!',
  'results': 'Results',
  'backButton': 'Return',
  'value1': '{value}',
  'value2': '{value}',
  'resultHeader': 'Comparison Results',
  'feature1': 'ValueWheel',
  'feature2': 'TravelCircle',
  'otherComing':'Other feature coming soon!',
  'createButton': 'Create a new ValueWheel',
  'createSessionTitle': 'Create session',
  'sessionCode': 'Code',
  'sessionReady': 'Session Ready',
  'shareCode': 'Share this code',
  'waitingPlayers': 'Waiting for players...',
};