const Map<String, String> finnishPack = {
  'appTitle': 'Arvokello',
  'welcome': 'Tervetuloa Arvokelloon!',
  'featureSelectTitle': 'Valitse, mitä haluat tehdä',
  'chooseModeTitle': 'Valitse pelitila',
  'individualMode': 'Yksilö',
  'groupMode': 'Ryhmä',
  'askNumberLabel': 'Kuinka monta arvoa haluat listata?',
  'continueButton': 'Jatka',
  'askWordsTitle': 'Anna arvot',
  'askValueLabel': 'Anna {index}. arvo',
  'amountLabel': 'Arvojen määrä: {amount}',
  'compareLabel': 'Valitse vaihtoehdoista.',
  'compareTitle': 'Vertailut valmiit!',
  'results': 'Tulokset',
  'backButton': 'Takaisin',
  'value1': '{value}',
  'value2': '{value}',
  'resultHeader': 'Vertailun tulokset',
  'feature1': 'Arvokello',
  'feature2': 'Reissurinki',
};